### PR TITLE
fix issue where romajii language users get wrong series && Add proper scraping for one piece/detective conan

### PR DESCRIPTION
**Pull request by jkaw**
fixing zambux's bug. 
You can set language to romajii and it should now search for the english title on trakt and get the proper episodes
Before it was searching the japanese title only which trakt does not handle nicely

### CODE REVIEW

**Comment by jkaw** [comment]
Also added code to improve scraping for one piece and detective conan. Was only going to do one piece ,but figured detective conan has a similar number of episodes.

**Comment by TaiDak** [comment]
Sorry for bringing this up, but cached episodes for one piece don't show up for me, unless I manually add them to my debrid cloud.

**Comment by jkaw** [comment]
Yes I just ran into that myself. I have a fix for it right now.

**Comment by TaiDak** [comment]
Testing the betas, works perfectly in beta 10, beta 11 breaks something.

**Comment by jkaw** [comment]
Yeah, I had to fix something. Anilist did something recently to their aliases and I had to change the code @Goldenfreddy0703 is preparing a release now.

**Comment by jkaw** [comment]
@TaiDak new beta is out with fix. Redownload the repo, install the beta, and let me know. It should be fixed now.

**Comment by TaiDak** [comment]
@jkaw yeah, one piece on beta 17 doesn't show any sources apart from gogo embeds

**Comment by jkaw** [comment]
Yeah, that one was my fault. It was late and I was being lazy. Should be fixed in latest when it gets released.

**Pull request merged**
